# Generated by Django 2.0.2 on 2018-07-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='age_preference',
            field=models.CharField(choices=[('C', 'Children are valued the most by the majority of people.'), ('A', 'Adults are valued the most by the majority of people.'), ('O', 'The elderly are valued the most by the majority of people.')], default='A', max_length=2),
        ),
    ]
